### ISSUE TITLE
HTTPS-Download

### ISSUE THREAD

**Issue by hoppfrosch** [joedf/AEI.ahk#1]
As https://autohotkey.com uses https-protocol rather than http since a longer period now, the script fails downloading the latest AHK-version from https://autohotkey.com/download/ahk-install.exe as the script still uses http://autohotkey.com/download/ahk-install.exe

Make downloading from https work

**Comment by joedf** [comment]
Weird... It still works fine for me.
What is your system? Paste me the AEI ;)
Also, maybe try changing in the script: `http://ahkscript.org/download/1.1/version.txt` and `http://ahkscript.org/download/ahk-install.exe` to `autohotkey.com`?
I'm not sure if https affects the downloading process...

**Comment by hoppfrosch** [comment]
Hmmmm.... I updated Autohotkey yesterday manually, so I cannot reproduce the error ATM, since the error occured during update. As far as I remember (I'm getting old lately ;-)) the error occurs when I tried to update to newer AHK-version. It failed and said something about SSL and secured connection ... that's why my clue was AEI.ahk has to use https ...

This is my AEI:

AutoHotkey :            v1.1.23.05 Unicode 32-bit (Installed)
SystemModel :           H67A-USB3-B3
SystemCPU :             Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
SystemGPU :             NVIDIA GeForce 210  v8.17.13.142 @ 1024.00 MB RAM
SystemType :            x64-based PC
SystemRAM :             8175 MB
SystemOS :              WIN_7 64-bit Service Pack 1 v6.1.7601 (WIN32_NT)
SystemUptime :          0 days 0 hours 16 mins 4 seconds
SystemLocale :          de-DE (0x0407)
SystemScreen :          1920x1200 (96 DPI)
A_AhkPath :             D:\Portable\PortableApps\AutoHotkey\App\AutoHotkey.exe
Ahk_CompilerPath :      D:\Portable\PortableApps\AutoHotkey\App\Compiler\Ahk2Exe.exe
Ahk_WindowSpyPath :     D:\Portable\PortableApps\AutoHotkey\App\AU3_Spy.exe
MPRESS_IsPresent :      0 (false)

**Comment by joedf** [comment]
Wow... sorry about the late reply... :p
Is it working now?

**Comment by hoppfrosch** [comment]
Sorry about the late reply ... ;-)

Yupp - it seems to have been a temporary issue. I simply forget about this issue and forgot to close it therefore as "INVALID"

=> INVALID
